---
title: "Explore model outputs"
author: "M Lotto & E Rees"
date: "2022"
output:  
  html_document:
    toc: true
    toc_depth: 4
    toc_float: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, fig.height=7, fig.width=15)
```

```{r}
pacman::p_load("tidyverse", "here", "RColorBrewer", "rmarkdown", "cowplot", "pROC", "ggpubr", "kableExtra")

# Prepare data
df.lepto <- readRDS(here("data_use", "prov_cases.rds"))
pop <- readRDS(here("data_use", "pop.rds"))

data.lepto <- df.lepto %>% 
  left_join(pop) %>% 
  arrange(prov, year, month)

df.er <- data.lepto %>% filter(prov=="Entre Ríos")
df.sf <- data.lepto %>% filter(prov=="Santa Fe")

# Functions
plot.prob <- function(data, trigger, titles){
  data %>%
    mutate(prob.out=ifelse(prob.out<trigger[[1]], 0, prob.out)) %>% 
    ggplot(aes(x=month, y=year, fill=prob.out)) +
    geom_raster() +
    labs(title=titles, x="Month", y="Year") +
    scale_fill_gradientn(name="P(outbreak)", colours=brewer.pal(9, "PuRd"), limits=c(0,1)) + 
    geom_text(aes(label=outb), fontface=2, alpha=0.7, size=3) +
    scale_y_continuous(breaks=c(2009:2020), labels=c(2009:2020), expand=expansion(0)) +
    scale_x_continuous(breaks=c(1:12), labels=c(1:12), expand=expansion(0)) +
    theme_bw() +
    theme(legend.position="right",
          title=element_text(size=7))
}

roc.pt <- function(roc, trigger, titles){
  ggroc(roc) + # Create ROC curve using ggplot
    geom_segment(aes(x=1, xend=0, y=0, yend=1), color="darkgrey", linetype="dashed") + # Add diagonal line
    geom_point(aes(x=trigger[[2]], y=trigger[[3]]), shape=1, size=5, col="red") + #
    geom_text(data=trigger, aes(x=trigger[[2]]+0.05, y=trigger[[3]]+0.05, label=round(trigger[[1]], 2))) + # Add local maximal value
    geom_text(aes(x=0.3, y=0.05, label=paste0("AUC: ", round(roc$auc, 2)))) +
    labs(x="1-Specificity", y="Sensitivity", title=titles) +
    theme_bw() +
    theme(title=element_text(size=7))
}

plot.ts <- function(data, n, titles){
  data[["outb.prob"]][[n]] %>% 
    mutate(median=matrixStats::rowQuantiles(data[["post.samples"]][[n]], cols=c(1:1000), probs=0.5),
           lower=matrixStats::rowQuantiles(data[["post.samples"]][[n]], cols=c(1:1000), probs=0.025),
           upper=matrixStats::rowQuantiles(data[["post.samples"]][[n]], cols=c(1:1000), probs=0.975)) %>% 
    ggplot(aes(x=date)) +
    geom_line(aes(y=cases, col="Cases")) +
    geom_line(aes(y=median, col="Predicted")) +
    geom_ribbon(aes(ymin=lower, ymax=upper), alpha=0.3) +
    scale_color_manual(name="", 
                       values=c("Cases"="grey20", "Predicted"="blue")) +
    labs(title=titles, x="",y="") +
    scale_x_date(date_breaks="1 year", date_labels="%Y") +
    theme_bw() +
    theme(legend.position="none",
          axis.text.x=element_text(angle=25, hjust=1))
}

# Prediction models
er.preds <- readRDS(here("model_out", "er_preds.rds"))
sf.preds <- readRDS(here("model_out", "sf_preds.rds"))

labs.er <- c("seasonal", "+nino.2", "+nino.3", "+nino34.4", "+par.1+prcp.1")
labs.sf <- c("seasonal", "+nino.2", "+nino.3", "+par.1+prcp.1")
```

# Outputs {.tabset}
## Entre Ríos
### Outbreak probability
```{r}
t1 <- c("seasonal", "nino2", "nino3", "nino4", "par1+prcp1")

plots <- vector(mode="list", length=5)
for(i in 1:5){
  plots[[i]] <- plot.prob(er.preds$outb.prob[[i]], er.preds$trigger[[i]], titles=t1[i])
}

cowplot::plot_grid(plots[[1]], plots[[2]], plots[[3]],
                   plots[[4]], plots[[5]], ncol=3)
```

### ROC curves
```{r}
plots <- vector(mod="list", length=5)
for(i in 1:5){
    plots[[i]] <- roc.pt(roc=er.preds$roc[[i]], trigger=er.preds$trigger[[i]], titles=t1[i])
}

cowplot::plot_grid(plots[[1]], plots[[2]], plots[[3]],
                   plots[[4]], plots[[5]], ncol=3)
```

### Observed vs predicted
```{r}
plots <- vector(mod="list", length=5)
for(i in 1:5){
    plots[[i]] <- plot.ts(data=er.preds, n=i, titles=t1[i])
}

leg <- cowplot::get_legend(plots[[1]]+theme(legend.position="right"))

cowplot::plot_grid(plots[[1]], plots[[2]], plots[[3]],
                   plots[[4]], plots[[5]], leg, ncol=3)

```

## Santa Fe
### Outbreak probability
```{r fig.height=7}
t1 <- c("seasonal", "nino3", "nino4", "par0+prcp2")

plots <- vector(mode="list", length=4)
for(i in 1:4){
  plots[[i]] <- plot.prob(sf.preds$outb.prob[[i]], sf.preds$trigger[[i]], titles=t1[i])
}

cowplot::plot_grid(plots[[1]], plots[[2]], plots[[3]],
                   plots[[4]], ncol=3)
```

### Plot ROC curves
```{r}
plots <- vector(mod="list", length=4)
for(i in 1:4){
    plots[[i]] <- roc.pt(roc=sf.preds$roc[[i]], trigger=sf.preds$trigger[[i]], titles=t1[i])
}

cowplot::plot_grid(plots[[1]], plots[[2]], plots[[3]],
                   plots[[4]], ncol=3)
```

### Observed vs predicted
```{r}
plots <- vector(mod="list", length=5)
for(i in 1:4){
    plots[[i]] <- plot.ts(data=er.preds, n=i, titles=t1[i])
}

leg <- cowplot::get_legend(plots[[1]]+theme(legend.position="right"))

cowplot::plot_grid(plots[[1]], plots[[2]], plots[[3]],
                   plots[[4]], leg, ncol=3)
```
